dota_chat/urls.py
from django.contrib import admin
from django.urls import path, re_path, include

from . import views
from . import view_utils as view_utils

from django.contrib.auth import views as auth_views


urlpatterns = [
    # home
    re_path(r'^$', views.index, name='index'),
    re_path(r'^login/$', auth_views.LoginView.as_view(template_name='dota_chat/login.html'),name='auth_login'),
    re_path(r'^logout/$', auth_views.LogoutView.as_view(template_name='dota_chat/logged_out.html'), name='auth_logout'),
    re_path(r'^dashboard/$', views.dashboard, name='dashboard'),
    
    re_path(r'^heroes/$',views.HeroListView.as_view(),name='hero_list_view'),
    re_path(r'^heroes/(?P<slug>[\w-]+)/$',views.HeroDetailView.as_view(),name='hero_detail_view'),

    re_path(r'abilities/$',views.AbilityListView.as_view(),name='ability_list_view'),
    re_path(r'abilities/(?P<pk>[0-9]+)/$',views.AbilityDetailView.as_view(),name='ability_detail_view'),

    re_path(r'^players/$',views.PlayerListView.as_view(),name='player_list_view'),
    re_path(r'^players/(?P<slug>[\w-]+)/$',views.PlayerDetailView.as_view(),name='player_detail_view'),

    re_path(r'^users/$',views.UserListView.as_view(),name='user_list_view'),
    re_path(r'^users/(?P<pk>[0-9]+)/$',views.UserDetailView.as_view(),name='user_detail_view'),

    re_path(r'draft/$',views.DraftView.as_view(),name='draft_view'),

]

urlpatterns_functions = [
    re_path(r'^winRatePlot/(?P<hero_id>[0-9]+)/$', view_utils.winRatePlot, name='win_rate_plot'),
    re_path(r'^winLossChatPlot/(?P<hero_id>[0-9]+)/$', view_utils.winLossChatPlot, name='win_loss_chat_plot'),
    re_path(r'^map/$', view_utils.map, name='map'),
    re_path(r'^temporal_histograms/$', view_utils.temporal_histograms, name='temporal_histograms'),
    re_path(r'^hero_popularity_histogram/$', view_utils.hero_popularity_histogram, name='hero_popularity_histogram'),
    re_path(r'^region_histogram/$', view_utils.region_histogram, name='region_histogram'),
    re_path(r'^generateRandomDraft/$',view_utils.generateRandomDraft,name='generate_random_draft'),
    re_path(r'^predictHeroPick/$',view_utils.predictHeroPick,name='predict_hero_pick'),

]

urlpattern_lists = [
    re_path(r'^addAbilityBehaviors/$', views.addAbilityBehaviors, name='add_ability_behaviors'),
    re_path(r'^removeAbilityBehaviors/$', views.removeAbilityBehaviors, name='remove_ability_behaviors'),
    re_path(r'^dynamic_user_search/', views.dynamic_user_search,name='dynamic_user_search'),
    re_path(r'^user_search_redirect/', views.user_search_redirect,name='user_search_redirect'),

]

urlpatterns += urlpatterns_functions
urlpatterns += urlpattern_lists

pipe_of_insight/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,re_path,include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^', include('dota_chat.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dota_chat/forms.py
import os,pdb,sys

from . import models as models

from django import forms

class DraftForm(forms.Form):

    def __init__(self,*args,**kwargs):
        super().__init__(*args, **kwargs)
        self.label_suffix = ''  # Removes : as label suffix

    allHeros = models.Hero.objects.all().order_by('slug')

    nullChoiceList = [('','(Empty)')]
    heroChioces = [(h.valveID,h.prettyName) for h in allHeros]
    heroChioces = nullChoiceList+heroChioces

    allySlot1_hero = forms.ChoiceField(required=False,choices=heroChioces,label = 'Your Hero (optional):')
    allySlot2_hero = forms.ChoiceField(required=False,choices=heroChioces,label = 'Allied Hero:')
    allySlot3_hero = forms.ChoiceField(required=False,choices=heroChioces,label = 'Allied Hero:')
    allySlot4_hero = forms.ChoiceField(required=False,choices=heroChioces,label = 'Allied Hero:')
    allySlot5_hero = forms.ChoiceField(required=False,choices=heroChioces,label = 'Allied Hero:')

    allySlot1_user = forms.CharField(required=False,widget=forms.TextInput(attrs={'class':'form-control','id':'allySearch_1'}),label = 'Your Steam Name')
    allySlot2_user = forms.CharField(required=False,widget=forms.TextInput(attrs={'class':'form-control','id':'allySearch_2'}),label = 'Steam User')
    allySlot3_user = forms.CharField(required=False,widget=forms.TextInput(attrs={'class':'form-control','id':'allySearch_3'}),label = 'Steam User')
    allySlot4_user = forms.CharField(required=False,widget=forms.TextInput(attrs={'class':'form-control','id':'allySearch_4'}),label = 'Steam User')
    allySlot5_user = forms.CharField(required=False,widget=forms.TextInput(attrs={'class':'form-control','id':'allySearch_5'}),label = 'Steam User')

    enemySlot1_hero = forms.ChoiceField(required=False,choices=heroChioces,label = 'Enemy Hero:')
    enemySlot2_hero = forms.ChoiceField(required=False,choices=heroChioces,label = 'Enemy Hero:')
    enemySlot3_hero = forms.ChoiceField(required=False,choices=heroChioces,label = 'Enemy Hero:')
    enemySlot4_hero = forms.ChoiceField(required=False,choices=heroChioces,label = 'Enemy Hero:')
    enemySlot5_hero = forms.ChoiceField(required=False,choices=heroChioces,label = 'Enemy Hero:')

    enemySlot1_user = forms.CharField(required=False,widget=forms.TextInput(attrs={'class':'form-control','id':'enemySearch_1'}),label = 'Steam User')
    enemySlot2_user = forms.CharField(required=False,widget=forms.TextInput(attrs={'class':'form-control','id':'enemySearch_2'}),label = 'Steam User')
    enemySlot3_user = forms.CharField(required=False,widget=forms.TextInput(attrs={'class':'form-control','id':'enemySearch_3'}),label = 'Steam User')
    enemySlot4_user = forms.CharField(required=False,widget=forms.TextInput(attrs={'class':'form-control','id':'enemySearch_4'}),label = 'Steam User')
    enemySlot5_user = forms.CharField(required=False,widget=forms.TextInput(attrs={'class':'form-control','id':'enemySearch_5'}),label = 'Steam User')


    def assess_draft(self):
        # send email using the self.cleaned_data dictionary
        pass

dota_chat/views.py
import os,sys,shutil,pdb,glob,logging,datetime,tarfile,json,copy
import requests
import numpy as np 

from . import models as models
from . import tables as tables
from . import forms as forms
from . import view_utils as view_utils

from django.conf import settings
from django.db.models import Q, F, Avg

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

from django.http import HttpResponse, JsonResponse 
from django.http import HttpResponseRedirect, HttpResponseServerError, HttpResponseForbidden

from django.urls import reverse, reverse_lazy

from django.utils import timezone
from django.utils.encoding import smart_str

from django.views.generic import View, ListView, DetailView
from django.views.generic import UpdateView, DeleteView, CreateView
from django.views.generic.edit import FormView

from django.views.generic.base import ContextMixin
from django.views.decorators.csrf import csrf_protect, ensure_csrf_cookie
from django.shortcuts import render,redirect,get_object_or_404

from django_tables2 import RequestConfig

from bokeh.embed import server_document

logger = logging.getLogger(__name__)


# Create your views here.

class DraftView(FormView):
    template_name = 'dota_chat/draft/draft_view.html'
    form_class = forms.DraftForm
    success_url = reverse_lazy('draft_view') # wow
    context_object_name = 'viewContent'

    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        context['user'] = self.request.user.username
        if context['user'] == '':
            context['user'] = 'Anonymous'

        randomDraftList = view_utils.generateRandomDraft()
        defaultData = {}

        for i,heroSlug in enumerate(randomDraftList):
            hero = models.Hero.objects.get(slug=heroSlug)
            if i < 5:
                keyBase = 'allySlot{}_'.format(i+1)
                userKeyBase = '{}{}'.format(keyBase,'user')
                heroKeyBase = '{}{}'.format(keyBase,'hero')
                if i == 0:
                    defaultData[userKeyBase] = 'Your profile name'
                    defaultData[heroKeyBase] = ''
                else:
                    defaultData[userKeyBase] = 'Ally {} profile'.format(i)
                    defaultData[heroKeyBase] = hero.valveID

            elif i >= 5 and i < 10:
                keyBase = 'enemySlot{}_'.format(i+1-5)
                userKeyBase = '{}{}'.format(keyBase,'user')
                heroKeyBase = '{}{}'.format(keyBase,'hero')
                defaultData[userKeyBase] = 'Enemy {} profile'.format(i)
                defaultData[heroKeyBase] = hero.valveID
            else:
                pass

        context['form'] = forms.DraftForm(defaultData)

        return {self.context_object_name: context}

    def post(self,request,*args,**kwargs):

        if 'form' in request.POST:
            form_class = self.form_class
            self.form_name = 'form'

        form = self.get_form(form_class)

        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(**{self.form_name: form})

    def form_valid(self, form):
        # This method is called when valid form data has been POSTed.
        # It should return an HttpResponse.
        sortList = view_utils.predictHeroPick(form.cleaned_data)
        bestHeroSlug = sortList[-1][0]
        #bestHero = models.Hero.objects.get(slug=bestHeroSlug)

        return HttpResponseRedirect(reverse('hero_detail_view',kwargs={'slug':bestHeroSlug}))




class HeroListView(ListView):
    ''' ListView for heros in Dota 2 '''
    model = models.Hero 
    template_name = 'dota_chat/hero/hero_list_view.html'
    context_object_name = 'viewContent'

    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        context['user'] = self.request.user.username
        if context['user'] == '':
            context['user'] = 'Anonymous'

        table = tables.HeroListTable(models.Hero.objects.all().order_by('name'))
        RequestConfig(self.request,paginate={'per_page':15}).configure(table)
        context['table'] = table

        return {self.context_object_name: context}


class HeroDetailView(DetailView):
    ''' DetailView for heros in Dota 2 '''
    model = models.Hero
    template_name = 'dota_chat/hero/hero_detail_view.html'
    context_object_name = 'viewContent'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user'] = self.request.user.username
        if context['user'] == '':
            context['user'] = 'Anonymous'

        # construct abilities
        allAbilities = list(self.object.abilities.all().order_by('abilitySlot'))
        allAbilityBehaviors = list(models.AbilityBehaviors.objects.all().order_by('behavior'))

        abilities = []

        for ability in allAbilities:
            isCoreSpell = ability.behavior.filter(behavior='Core Spell').exists()
            isAghsSpell = ability.behavior.filter(behavior='Granted By Scepter').exists()
            isHidden = ability.behavior.filter(behavior='Hidden').exists()

            if ability.img and (isCoreSpell or isAghsSpell) and not isHidden:
                abilities.append(ability)

        context['abilities'] = abilities

        # construct chat
        chatLog = {}
        allPlayers = list(self.object.player_set.all())
        #allPlayers = []
        for player in allPlayers:
            playerName = player.name
            allChat = player.chatentry_set.all()
            for chat in allChat:
                entry = (chat.chatTime,chat.chatText)
                if playerName in chatLog.keys():
                    chatLog[playerName].append(entry)
                else:
                    chatLog[playerName] = [entry]
            if len(chatLog) > 5:
                break
        context['chat'] = chatLog

        context['allAbilityBehaviors'] = []
        context['allBehaviorColors'] = []

        for abilityBehavior in allAbilityBehaviors:
            context['allAbilityBehaviors'].append(abilityBehavior)
            context['allBehaviorColors'].append(abilityBehavior.color)

        return {self.context_object_name: context}


class AbilityListView(ListView):
    ''' ListView for abilities in Dota 2 '''
    model = models.HeroAbility 
    template_name = 'dota_chat/hero/ability_list_view.html'
    context_object_name = 'viewContent'

    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        context['user'] = self.request.user.username
        if context['user'] == '':
            context['user'] = 'Anonymous'

        table = tables.AbilityListTable(models.HeroAbility.objects.all().order_by('name'))
        RequestConfig(self.request,paginate={'per_page':50}).configure(table)
        context['table'] = table

        return {self.context_object_name: context}


class AbilityDetailView(DetailView):
    ''' DetailView for abilities in Dota 2 '''
    model = models.HeroAbility
    template_name = 'dota_chat/hero/ability_detail_view.html'
    context_object_name = 'viewContent'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user'] = self.request.user.username
        if context['user'] == '':
            context['user'] = 'Anonymous'
        return {self.context_object_name: context}

class PlayerListView(ListView):
    ''' List view for all players '''
    model = models.Player 
    template_name = 'dota_chat/player/player_list_view.html'
    context_object_name = 'viewContent'

    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        context['user'] = self.request.user.username
        if context['user'] == '':
            context['user'] = 'Anonymous'

        table = tables.PlayerListTable(models.Player.objects.all().order_by('name'))
        RequestConfig(self.request,paginate={'per_page':15}).configure(table)
        context['table'] = table

        return {self.context_object_name: context}

class PlayerDetailView(DetailView):
    ''' DetailView for players '''
    model = models.Player
    template_name = 'dota_chat/player/player_detail_view.html'
    context_object_name = 'viewContent'

    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        context['user'] = self.request.user.username
        if context['user'] == '':
            context['user'] = 'Anonymous'

        # construct chat
        chatLog = {}
        #allPlayers = list(self.object.player_set.all())
        playerName = self.object.name
        allChat = self.object.chatentry_set.all()
        for chat in allChat:
            entry = (chat.chatTime,chat.chatText)
            if playerName in chatLog.keys():
                chatLog[playerName].append(entry)
            else:
                chatLog[playerName] = [entry]
        context['chat'] = chatLog

        return {self.context_object_name: context}


class UserListView(ListView):
    ''' ListView for Steam users '''
    model = models.SteamUser
    template_name = 'dota_chat/user/user_list_search.html'
    context_object_name = 'viewContent'

    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        context['user'] = self.request.user.username
        if context['user'] == '':
            context['user'] = 'Anonymous'

        table = tables.UserListTable(models.SteamUser.objects.all().order_by('name'))
        RequestConfig(self.request,paginate={'per_page':15}).configure(table)
        context['table'] = table

        return {self.context_object_name: context}


class UserDetailView(DetailView):
    ''' DetailView for players '''
    model = models.SteamUser

dota_chat/templates/dota_chat/draft/header_draft.html
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Pipe of Insight</title>
    <meta charset="utf-8" />
    {% load staticfiles %}
    <meta name="viewport" content = "width=device-width, initial-scale=1.0"/>

    <!-- Load jquery -->    
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" 
            integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" 
            crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"></script>

    <!-- Load popper --> 
    <!-- This has to be before bootstrap if you have dropdowns -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" 
            integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" 
            crossorigin="anonymous"></script>


    <!--  Load bootstrap -->
    <link rel="stylesheet" href='https://cdnjs.cloudflare.com/ajax/libs/admin-lte/2.4.18/css/AdminLTE.css' type='text/css'>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>



    <link href='https://cdn.pydata.org/bokeh/release/bokeh-1.3.4.min.css' rel='stylesheet' type='text/css'>
    <link href='https://cdn.pydata.org/bokeh/release/bokeh-widgets-1.3.4.min.css' rel='stylesheet' type='text/css'>
    <script src='https://cdn.pydata.org/bokeh/release/bokeh-1.3.4.min.js'></script>
    <script src='https://cdn.pydata.org/bokeh/release/bokeh-widgets-1.3.4.min.js'></script>
    <script src="https://kit.fontawesome.com/0bd5cf1d21.js"></script>



    <style type="text/css">
        html,
        body {height:100%;
              background-color: #fafafa !important;
        },
        .tab { margin-left: 40px; }

        .popover-content {
          height: 180px;  
          width: 200px;  
        }

        .popover-footer {
          margin: 0;
          padding: 8px 14px;
          font-size: 14px;
          font-weight: 400;
          line-height: 18px;
          background-color: #F7F7F7;
          border-bottom: 1px solid #EBEBEB;
          border-radius: 5px 5px 0 0;
        }

        .githubbutton {
            position: relative;
            overflow: visible;
            display: inline-block;
            padding: 0.5em 1em;
            border: 1px solid #d4d4d4;
            margin: 0;
            text-decoration: none;
            text-align: center;
            text-shadow: 1px 1px 0 #fff;
            font:11px/normal sans-serif;
            color: #333;
            white-space: nowrap;
            cursor: pointer;
            outline: none;
            background-color: #ececec;
            background-image: -webkit-gradient(linear, 0 0, 0 100%, from(#f4f4f4), to(#ececec));
            background-image: -moz-linear-gradient(#f4f4f4, #ececec);
            background-image: -ms-linear-gradient(#f4f4f4, #ececec);
            background-image: -o-linear-gradient(#f4f4f4, #ececec);
            background-image: linear-gradient(#f4f4f4, #ececec);
            -moz-background-clip: padding; /* for Firefox 3.6 */
            background-clip: padding-box;
            border-radius: 0.2em;
            /* IE hacks */
            zoom: 1;
            *display: inline;
        }
        .githubbutton.pill {
            border-radius: 50em;
        }
    </style>


    <link href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css" rel="stylesheet" type="text/css" />

    <!-- Load the cookie stuff -->    
    <script src="https://cdn.jsdelivr.net/npm/js-cookie@2/src/js.cookie.min.js"></script>

    <!-- select all functionality -->
    <script type="text/javascript" >

        function isEmpty(obj) {
            for(var key in obj) {
                if(obj.hasOwnProperty(key))
                    return false;
            }
            return true;
        }

        // ajax setup stuff
        function csrfSafeMethod(method) {
            // these HTTP methods do not require CSRF protection
            return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
        }

        var csrftoken = Cookies.get('csrftoken');
        $.ajaxSetup({
            beforeSend: function(xhr, settings) {
             if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                 xhr.setRequestHeader("X-CSRFToken", csrftoken);
             }
            }
        });

        // is this even remotely plausible?
        // $('#predictButton').on('click', function () {
        //     // get the fields in the canvas FOV
        //     $.ajax({
        //         type : 'POST',
        //         url: "{% url 'predict_hero_pick' %}",
        //         data: {
        //             "#id_enemySlot1_hero": $("#id_enemySlot1_hero").value,
        //             "#id_enemySlot2_hero": $("#id_enemySlot2_hero").value,
        //             "#id_enemySlot3_hero": $("#id_enemySlot3_hero").value,
        //             "#id_enemySlot4_hero": $("#id_enemySlot4_hero").value,
        //             "#id_enemySlot5_hero": $("#id_enemySlot5_hero").value,
        //             "#id_myTeamSlot1_hero": $("#id_myTeamSlot1_hero").value,
        //             "#id_myTeamSlot2_hero": $("#id_myTeamSlot2_hero").value,
        //             "#id_myTeamSlot3_hero": $("#id_myTeamSlot3_hero").value,
        //             "#id_myTeamSlot4_hero": $("#id_myTeamSlot4_hero").value,
        //             "#id_myTeamSlot5_hero": $("#id_myTeamSlot5_hero").value,
        //         },
        //         dataType: 'json',
        //         success : function(retData) {
        //             // now send the paperscript to draw the field (only if we got verts)
        //             if (!isEmpty(retData)) {
        //                 // turn this into arrays
        //                 var resArr = JSON.parse(retData);
        //                 // for (i = 0; i < resArr[0].length; i++) {
        //                 //     initDrawSingleField(resArr[0][i],resArr[1][i],resArr[2][i])
        //                 // }
        //                 console.log(retData)
        //             }
        //         }
        //     })
        // }

        $(document).ready(function(){ 
            $("#allySearch_1").autocomplete({
                source: '{% url "dynamic_user_search" %}',
                minLength: 3,
                open: function(){
                    setTimeout(function () {
                        $('.ui-autocomplete').css('z-index', 99);
                    }, 0);
                },
                select: function(event, ui) { 
                    $("#allySearch_1").val(ui.item.label);
                }
              });

            $("#allySearch_2").autocomplete({
                source: '{% url "dynamic_user_search" %}',
                minLength: 3,
                open: function(){
                    setTimeout(function () {
                        $('.ui-autocomplete').css('z-index', 99);
                    }, 0);
                },
                select: function(event, ui) { 
                    $("#allySearch_2").val(ui.item.label);
                }
              });

            $("#allySearch_3").autocomplete({
                source: '{% url "dynamic_user_search" %}',
                minLength: 3,
                open: function(){
                    setTimeout(function () {
                        $('.ui-autocomplete').css('z-index', 99);
                    }, 0);
                },
                select: function(event, ui) { 
                    $("#allySearch_3").val(ui.item.label);
                }
              });

            $("#allySearch_4").autocomplete({
                source: '{% url "dynamic_user_search" %}',
                minLength: 3,
                open: function(){
                    setTimeout(function () {
                        $('.ui-autocomplete').css('z-index', 99);
                    }, 0);
                },
                select: function(event, ui) { 
                    $("#allySearch_4").val(ui.item.label);
                }
              });

            $("#allySearch_5").autocomplete({
                source: '{% url "dynamic_user_search" %}',
                minLength: 3,
                open: function(){
                    setTimeout(function () {
                        $('.ui-autocomplete').css('z-index', 99);
                    }, 0);
                },
                select: function(event, ui) { 
                    $("#allySearch_5").val(ui.item.label);
                }
              });






            $("#enemySearch_1").autocomplete({
                source: '{% url "dynamic_user_search" %}',
                minLength: 3,
                open: function(){
                    setTimeout(function () {
                        $('.ui-autocomplete').css('z-index', 99);
                    }, 0);
                },
                select: function(event, ui) { 
                    $("#enemySearch_1").val(ui.item.label);
                }
              });

            $("#enemySearch_2").autocomplete({
                source: '{% url "dynamic_user_search" %}',
                minLength: 3,
                open: function(){
                    setTimeout(function () {
                        $('.ui-autocomplete').css('z-index', 99);
                    }, 0);
                },
                select: function(event, ui) { 
                    $("#enemySearch_2").val(ui.item.label);
                }
              });

            $("#enemySearch_3").autocomplete({
                source: '{% url "dynamic_user_search" %}',
                minLength: 3,
                open: function(){
                    setTimeout(function () {
                        $('.ui-autocomplete').css('z-index', 99);
                    }, 0);
                },
                select: function(event, ui) { 
                    $("#enemySearch_3").val(ui.item.label);
                }
              });

            $("#enemySearch_4").autocomplete({
                source: '{% url "dynamic_user_search" %}',
                minLength: 3,
                open: function(){
                    setTimeout(function () {
                        $('.ui-autocomplete').css('z-index', 99);
                    }, 0);
                },
                select: function(event, ui) { 
                    $("#enemySearch_4").val(ui.item.label);
                }
              });

            $("#enemySearch_5").autocomplete({
                source: '{% url "dynamic_user_search" %}',
                minLength: 3,
                open: function(){
                    setTimeout(function () {
                        $('.ui-autocomplete').css('z-index', 99);
                    }, 0);
                },
                select: function(event, ui) { 
                    $("#enemySearch_5").val(ui.item.label);
                }
              });





        });

    </script>

</head>


<body class="body" style="background-color:#fcfcfc">
    <!-- Youser info -->
    <div class="container mt-3">
        <div class="row justify-content-end">
            <div class="col-auto">
                <p>Hi {{ viewContent.user }}
                <a href="{{ viewContent.VIR_DIR }}/logout/" class="githubbutton pill">Logout</a>
                </p>
            </div>
        </div>
    </div>

    
    <!-- Title -->
    <div class="container-fluid">
        <br>
        <center>
            <h3>
                <a href="/"> Pipe of Insight </a>
            </h3>
        </center>
    </div>
    
    
{% block content %}
{% endblock %}
    

<!-- Close the main body and page -->    
</body>
</html>